version: "3.8"

services:
  postgres:
    image: postgres:17.2-alpine
    container_name: asyncly-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: asyncly_user
      POSTGRES_PASSWORD: asyncly_password
      POSTGRES_DB: asyncly_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: asyncly-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
